name: production build, lints, test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: install modules
        run: npm install

      - name: production build
        run: npm run build:prod

      - name: eslint
        run: npm run eslint

      - name: stylelint
        run: npm run stylelint

      - name: unit testing (jest)
        run: npm run test:jest

      - name: storybook build
        run: npm run storybook:build

      - name: screenshot testing (loki)
        run: npm run test:loki:ci
